version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - NODE_ENV=production
      - MORGAN_LOG=dev
      - DATABASE_URL=mongodb://mongo:27017/teamsho
      - DATABASE_NAME=teamsho
      - KAVENEGAR_API_KEY=4F51713338356A4559394A503748654C553746554C316466712F4E6B79394E73
      - JWT_SECRET=thisIs!secret
      - JWT_LIFE_TIME=7d
      - JWT_ALGORITHM=HS256
      - REDIS_DATABASE_HOST=redis
      - REDIS_DATABASE_PORT=6379
    depends_on: 
      - redis
      - mongo
    networks:
      - app-network
      - db-network
      
  mongo:
    image: 'mongo'
    networks:
      - db-network 

  redis:
    image: 'redis'
    networks:
      - db-network 

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on: 
      - app
    networks:
      - app-network 


networks:
  app-network:
  db-network: